-- Run against MySQL 8.0+ after creating database/user (README).
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 student_id VARCHAR(40) UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role ENUM('student','admin') NOT NULL DEFAULT 'student',
 suspended BOOLEAN NOT NULL DEFAULT FALSE,
 muted_until DATETIME NULL,
 can_upload BOOLEAN NOT NULL DEFAULT TRUE,
 can_add_course BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS courses (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(30) NOT NULL UNIQUE,
 title VARCHAR(200) NOT NULL,
 semester VARCHAR(60) NOT NULL,
 created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS uploaded_files (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL,
 filename VARCHAR(180) NOT NULL,
 mime VARCHAR(150) NOT NULL,
 data LONGBLOB NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resources (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 course_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL,
 type ENUM('Notes','Slides','Past Questions','Lab Sheet','Link') NOT NULL,
 link VARCHAR(2048) NOT NULL,
 version VARCHAR(30) NOT NULL DEFAULT 'v1.0',
 uploaded_by BIGINT UNSIGNED NOT NULL,
 status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
 download_count INT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(course_id) REFERENCES courses(id),
 FOREIGN KEY(uploaded_by) REFERENCES users(id),
 INDEX ix_resource_course_status(course_id,status),
 FULLTEXT KEY ft_resource_title(title)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_ratings (
 resource_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 stars TINYINT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(resource_id,user_id),
 CHECK(stars BETWEEN 1 AND 5),
 FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_downloads (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 resource_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 downloaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX ix_download_resource(resource_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS rooms (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 course_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL,
 host_id BIGINT UNSIGNED NOT NULL,
 scheduled_at DATETIME NOT NULL,
 capacity SMALLINT UNSIGNED NOT NULL,
 link VARCHAR(2048) NULL,
 status ENUM('active','closed') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(capacity BETWEEN 2 AND 50),
 FOREIGN KEY(course_id) REFERENCES courses(id),
 FOREIGN KEY(host_id) REFERENCES users(id),
 INDEX ix_rooms_schedule(course_id,scheduled_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS room_members (
 room_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(room_id,user_id),
 FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 course_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 body TEXT NOT NULL,
 reply_to_id BIGINT UNSIGNED NULL,
 pinned BOOLEAN NOT NULL DEFAULT FALSE,
 deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(course_id) REFERENCES courses(id),
 FOREIGN KEY(user_id) REFERENCES users(id),
 FOREIGN KEY(reply_to_id) REFERENCES messages(id) ON DELETE SET NULL,
 INDEX ix_messages_course_time(course_id,id),
 FULLTEXT KEY ft_message_body(body)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS message_files (
 message_id BIGINT UNSIGNED NOT NULL,
 file_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(message_id,file_id),
 FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE,
 FOREIGN KEY(file_id) REFERENCES uploaded_files(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 kind ENUM('resource','room','message','complaint') NOT NULL,
 reference_id BIGINT UNSIGNED NULL,
 reason TEXT NOT NULL,
 status ENUM('open','resolved','dismissed') NOT NULL DEFAULT 'open',
 handled_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id),
 FOREIGN KEY(handled_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX ix_report_status(status)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 text VARCHAR(500) NOT NULL,
 link VARCHAR(500) NULL,
 is_read BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 actor_id BIGINT UNSIGNED NULL,
 action VARCHAR(120) NOT NULL,
 target VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX ix_audit_time(created_at)
) ENGINE=InnoDB;
